#!/bin/bash
# FaviGen - Simple favicon generator
# Usage: ./generate.sh [svg-file] [output-dir]
# Or: ./generate.sh --template hexagon --color1 "#ff0000" --letter "A"

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

# Default values
TEMPLATE="hexagon"
COLOR1="#7c3aed"
COLOR2="#ec4899"
STROKE="#1a1a1a"
TEXT_COLOR="#ffffff"
LETTER="F"
OUTPUT_DIR="./output"
SVG_FILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --template)
            TEMPLATE="$2"
            shift 2
            ;;
        --color1)
            COLOR1="$2"
            shift 2
            ;;
        --color2)
            COLOR2="$2"
            shift 2
            ;;
        --letter)
            LETTER="$2"
            shift 2
            ;;
        --output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --help)
            echo "FaviGen - Simple favicon generator"
            echo ""
            echo "Usage:"
            echo "  From SVG file:    ./generate.sh input.svg [output-dir]"
            echo "  From template:    ./generate.sh --template [hexagon|circle|square] --letter X"
            echo ""
            echo "Options:"
            echo "  --template    Shape template (hexagon, circle, square)"
            echo "  --color1      Primary gradient color (hex)"
            echo "  --color2      Secondary gradient color (hex)"
            echo "  --letter      Letter/emoji for center"
            echo "  --output      Output directory"
            echo "  --help        Show this help"
            exit 0
            ;;
        *)
            if [[ -f "$1" ]]; then
                SVG_FILE="$1"
            else
                OUTPUT_DIR="${2:-./output}"
            fi
            shift
            ;;
    esac
done

# Check ImageMagick
if ! command -v magick &> /dev/null; then
    echo -e "${RED}✗ ImageMagick not installed${RESET}"
    echo "Install with: brew install imagemagick"
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo -e "${YELLOW}FaviGen - Favicon Generator${RESET}"
echo "================================"

# Generate from template or use provided SVG
if [[ -z "$SVG_FILE" ]]; then
    # Use template
    TEMPLATE_FILE="./templates/${TEMPLATE}.svg"
    if [[ ! -f "$TEMPLATE_FILE" ]]; then
        echo -e "${RED}✗ Template not found: $TEMPLATE${RESET}"
        exit 1
    fi

    # Generate SVG from template
    SVG_FILE="$OUTPUT_DIR/favicon.svg"
    sed -e "s|{{COLOR1}}|$COLOR1|g" \
        -e "s|{{COLOR2}}|$COLOR2|g" \
        -e "s|{{STROKE}}|$STROKE|g" \
        -e "s|{{TEXT_COLOR}}|$TEXT_COLOR|g" \
        -e "s|{{LETTER}}|$LETTER|g" \
        "$TEMPLATE_FILE" > "$SVG_FILE"

    echo -e "${GREEN}✓${RESET} Generated from template: $TEMPLATE"
else
    # Copy provided SVG
    cp "$SVG_FILE" "$OUTPUT_DIR/favicon.svg"
    SVG_FILE="$OUTPUT_DIR/favicon.svg"
    echo -e "${GREEN}✓${RESET} Using provided SVG"
fi

# Generate favicon sizes
echo -e "${GREEN}→${RESET} Generating favicon sizes..."
magick "$SVG_FILE" -resize 16x16 "$OUTPUT_DIR/favicon-16.png"
magick "$SVG_FILE" -resize 32x32 "$OUTPUT_DIR/favicon-32.png"
magick "$SVG_FILE" -resize 180x180 "$OUTPUT_DIR/apple-touch-icon.png"
magick "$SVG_FILE" -resize 192x192 "$OUTPUT_DIR/icon-192.png"
magick "$SVG_FILE" -resize 512x512 "$OUTPUT_DIR/icon-512.png"

# Create ICO
echo -e "${GREEN}→${RESET} Creating favicon.ico..."
magick "$OUTPUT_DIR/favicon-16.png" "$OUTPUT_DIR/favicon-32.png" "$OUTPUT_DIR/favicon.ico"

# Generate manifest.json
echo -e "${GREEN}→${RESET} Creating manifest.json..."
cat > "$OUTPUT_DIR/manifest.json" << EOF
{
  "name": "App",
  "short_name": "App",
  "icons": [
    {
      "src": "/icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "theme_color": "$COLOR1",
  "background_color": "#ffffff",
  "display": "standalone"
}
EOF

# Generate HTML snippet
cat > "$OUTPUT_DIR/favicon-html.txt" << EOF
<!-- Favicons - Generated by FaviGen -->
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="alternate icon" href="/favicon.ico">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.json">
EOF

echo ""
echo -e "${GREEN}✓ Success!${RESET} Favicons generated in: ${OUTPUT_DIR}/"
echo ""
echo "Files created:"
ls -1 "$OUTPUT_DIR" | sed 's/^/  - /'
echo ""
echo -e "HTML snippet saved to: ${OUTPUT_DIR}/favicon-html.txt"